#!/usr/bin/env python

if __name__ == "__main__":
    print "Starting Minion Plugin Service on localhost:8282"
    from minion.plugin_service.PluginServiceRestApi import app
    from bottle import run
    run(app, host='localhost', port=8282)
