#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import json
import sys
import time

import requests

if __name__ == "__main__":

   # minion-plugin-client task-engine-url plan-name configuration

   task_engine_url = sys.argv[1]
   plan_name = sys.argv[2]
   configuration = sys.argv[3]

   r = requests.put(task_engine_url + "/scan/create/" + plan_name, data=configuration)
   r.raise_for_status()
   print "CREATE RESPONSE", r.text
   create_response = r.json

   if create_response['success']:

      url = task_engine_url + "/scan/" + create_response['scan']['id'] + "/state"
      print "START REQUEST", url
      r = requests.post(url, 'START')
      r.raise_for_status()
      #print "START RESPONSE", r.text
      start_response = r.json

      if start_response['success']:

         token = None
         while True:

            url = task_engine_url + "/scan/" + create_response['scan']['id'] + "/results"
            if token: url += "?token=" + token
            print "RESULTS REQUEST", url
            r = requests.get(url)
            r.raise_for_status()
            print "STATUS RESPONSE", r.text
            results_response = r.json

            for session in results_response['scan']['sessions']:
               if len(session['issues']) > 0:
                  print "GOT ISSUES", session['issues']

            token = results_response['token']
            print "TOKEN", token
            if token is None:
               print "Token is null, so we are good"
               break

            time.sleep(1)
