#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import json
import sys
import time

import requests

if __name__ == "__main__":

   # minion-plugin-client task-engine-url plan-name configuration

   task_engine_url = sys.argv[1]
   plan_name = sys.argv[2]
   configuration = sys.argv[3]

   r = requests.put(task_engine_url + "/scan/create/" + plan_name, data=configuration)
   r.raise_for_status()
   print "CREATE RESPONSE", r.text
   create_response = r.json

   if create_response['success']:
      r = requests.post(task_engine_url + "/scan/" + create_response['scan']['id'] + "/state", 'START')
      r.raise_for_status()
      print "START RESPONSE", r.text
      start_response = r.json

      if start_response['success']:
         while True:
            r = requests.get(task_engine_url + "/scan/" + create_response['scan']['id'])
            r.raise_for_status()
            print "STATUS RESPONSE", r.text
            status_response = r.json
            if status_response['scan']['state'] != 'STARTED':
               break
            time.sleep(1)

         r = requests.get(task_engine_url + "/scan/" + create_response['scan']['id'] + "/results")
         r.raise_for_status()
         print "RESULTS", r.text
