#!/usr/bin/env python

if __name__ == "__main__":
    print "Starting Minion Task Engine on localhost:8181"
    from minion.task_engine.TaskEngineRestApi import app
    from bottle import run
    run(app, host='localhost', port=8181)
