#!/usr/bin/env python

import logging
from optparse import OptionParser
from minion.task_engine.api import app
from bottle import run

if __name__ == "__main__":
    
    parser = OptionParser()
    parser.add_option("--address", default="127.0.0.1")
    parser.add_option("--port", default=8181, type="int")
    parser.add_option("--debug", action="store_true")

    (options, args) = parser.parse_args()

    level = logging.DEBUG if options.debug else logging.INFO
    logging.basicConfig(level=level, format='%(asctime)s %(levelname)s %(message)s', datefmt='%y-%m-%d %H:%M:%S')
    logging.info("Starting Minion Task Engine on %s:%d" % (options.address, options.port))

    run(app, host=options.address, port=options.port)
